apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logdna-agent-pdns-atracker
  namespace: ibm-observe
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: logdna-agent
  template:
    metadata:
      labels:
        app: logdna-agent
    spec:
      serviceAccountName: logdna-agent
      containers:
        - name: logdna-agent-pdns-atracker
          image: {{ .Values.atracker_app.repository }}:{{ .Values.atracker_app.tag }}
          imagePullPolicy: Always
          env:
            - name: LOGDNA_AGENT_KEY
              valueFrom:
                secretKeyRef:
                  name: logdna-agent-key
                  key: logdna-agent-pdns-key
            - name: LOGDNA_HOST
              value: ingest.private.global.atracker.cloud.ibm.com
            - name: RUST_LOG
              value: info
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 20m
            limits:
              memory: 500Mi
          volumeMounts:
            - name: varlogat
              mountPath: /var/log/at/pdns
            - name: vardata
              mountPath: /var/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: mnt
              mountPath: /mnt
              readOnly: true
            - name: osrelease
              mountPath: /etc/os-release
            - name: logdnahostname
              mountPath: /etc/logdna-hostname
      volumes:
        - name: varlogat
          hostPath:
            path: /var/log/at/pdns
        - name: vardata
          hostPath:
            path: /var/data
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: mnt
          hostPath:
            path: /mnt
        - name: osrelease
          hostPath:
            path: /etc/os-release
        - name: logdnahostname
          hostPath:
            path: /etc/hostname
